# This Github Workflow automatically publishes Python Libraries (specifically Python Packages as Python Modules can't be uploaded via PyPi) to PyPi, whenever a Release of the Github Repository (containing the Python Library) is published.
name: Publish Python Library to PyPi on Release

# Specifies that the Github Workflow is only to be executed when a Release of the Github Repository (containing the Python Library) is published.
on:
  release:
    types: [published]

# Defines the processes of the Github Workflow that build and publish the Python Library.
jobs:

  # Job 1: Builds the Python Package, converting the source distribution (.py files with a pyproject.toml file for metadata) into a wheel distribution (a .tar.gz file and a .whl file) so that it is ready to be distributed.
  build:
    runs-on: ubuntu-latest # Creates a virtual Linux machine to complete Job 1 on.

    # Defines the steps to complete Job 1.
    steps:
      - name: Download Github Repository Content to Machine
        uses: actions/checkout@v4

      - name: Set up Python Environment on Machine
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Package Builder to Python Environment
        run: python -m pip install --upgrade build

      - name: Build Package
        run: python -m build

      # Uploads the artifacts (virtual files produced during the workflow operation - A.K.A the Python package wheel distribution files) to Github so that it can be used by other jobs.
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-dist
          path: dist/

  # Job 2: Uploads the Python Package to PyPi
  publish:
    needs: build # Specifies that the Python Package must be built before Job 2 commences.
    runs-on: ubuntu-latest # Creates a virtual Linux machine to complete Job 2 on.

    # Grants the permissions needed by the Github Workflow to access the security token to upload to PyPi.
    permissions:
      id-token: write

    # Defines the steps to complete Job 2.
    steps:
      # Downloads the artifacts (virtual files produced during another workflow operation - A.K.A the Python package wheel distribution files) previously uploaded to Github in Job 1 to the virtual Linux machine so that they can be used in Job 2.
      - name: Download Build Artifacts to Machine
        uses: actions/download-artifact@v4
        with:
          name: package-dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
